eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
  
